[build-system]
requires = [
    "setuptools >= 60.0.0",
    "setuptools-rust == 1.*, >= 1.10.0",
    "wheel >= 0.37.0",
]
build-backend = "setuptools.build_meta"

[tool.maturin]
features = ["pyo3/extension-module"]
